### ISSUE TITLE
OkHttpClient doesn't seem to be mandatory for native

### ISSUE THREAD

**Issue by rsvoboda** [quarkiverse/quarkus-github-api#29]
Readme says: The default HTTP connector is not working in native. Use the OkHttp connector provided by the GitHub API.

OkHttpClient doesn't seem to be mandatory for native. In my code I used just `github = new GitHubBuilder().withOAuthToken(ghToken).build();` and it worked fine, Quarkus 1.11.3, GraalVM CE 20.3.1.

Using https://github.com/rsvoboda/gh-exporter/tree/quarkus-github-api / https://github.com/rsvoboda/gh-exporter/blob/quarkus-github-api/src/main/java/io/quarkus/qe/metrics/GHRepositoryBaseMetrics.java#L30

**Comment by gsmet** [comment]
Yes, it is. The default HTTP connector does some dark magic reflection tricks to support methods not supported by old JDKs. I remember having issues with it and I don't think it has been resolved.

**Comment by gsmet** [comment]
This is the problematic code: https://github.com/hub4j/github-api/blob/master/src/main/java/org/kohsuke/github/GitHubHttpUrlConnectionClient.java#L167 .
